// Standard breed lists for cats and dogs

export const CAT_BREEDS = [
  'Abyssin',
  'American Curl',
  'American Shorthair',
  'Angora Turc',
  'Balinais',
  'Bengal',
  'Birman',
  'Bleu Russe',
  'Bombay',
  'British Longhair',
  'British Shorthair',
  'Burmese',
  'Burmilla',
  'Chartreux',
  'Cornish Rex',
  'Devon Rex',
  'Donskoy',
  'Egyptian Mau',
  'Européen',
  'Exotic Shorthair',
  'Havana Brown',
  'Highland Fold',
  'Highland Straight',
  'Khao Manee',
  'Korat',
  'LaPerm',
  'Maine Coon',
  'Mandarin',
  'Manx',
  'Mau Egyptien',
  'Munchkin',
  'Nebelung',
  'Norvégien',
  'Ocicat',
  'Oriental',
  'Persan',
  'Peterbald',
  'Pixie-Bob',
  'Ragdoll',
  'Sacré de Birmanie',
  'Savannah',
  'Scottish Fold',
  'Scottish Straight',
  'Selkirk Rex',
  'Siamois',
  'Sibérien',
  'Singapura',
  'Snowshoe',
  'Somali',
  'Sphynx',
  'Thaï',
  'Tonkinois',
  'Toyger',
  'Turc de Van',
  'York Chocolat',
]

export const DOG_BREEDS = [
  'Affenpinscher',
  'Akita Inu',
  'American Bully',
  'American Staffordshire Terrier',
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Beauceron',
  'Berger Allemand',
  'Berger Australien',
  'Berger Belge Malinois',
  'Berger Belge Tervueren',
  'Berger Blanc Suisse',
  'Berger de Beauce',
  'Berger de Brie',
  'Berger des Pyrénées',
  'Berger des Shetland',
  'Berger Hollandais',
  'Berger Picard',
  'Bichon Frisé',
  'Bichon Maltais',
  'Bobtail',
  'Border Collie',
  'Border Terrier',
  'Bouledogue Anglais',
  'Bouledogue Français',
  'Bouvier Bernois',
  'Bouvier des Flandres',
  'Boxer',
  'Braque Allemand',
  'Braque de Weimar',
  'Braque Français',
  'Braque Hongrois',
  'Briard',
  'Bull Terrier',
  'Cairn Terrier',
  'Cane Corso',
  'Caniche',
  'Carlin',
  'Cavalier King Charles',
  'Chihuahua',
  'Chow-Chow',
  'Cocker Anglais',
  'Cocker Américain',
  'Colley',
  'Corgi (Pembroke)',
  'Corgi (Cardigan)',
  'Coton de Tuléar',
  'Dalmatien',
  'Dobermann',
  'Dogue Allemand',
  'Dogue Argentin',
  'Dogue de Bordeaux',
  'Drahthaar',
  'Epagneul Breton',
  'Epagneul Papillon',
  'Eurasier',
  'Fox Terrier',
  'Golden Retriever',
  'Grand Caniche',
  'Griffon',
  'Griffon Korthals',
  'Hovawart',
  'Husky Sibérien',
  'Irish Wolfhound',
  'Jack Russell Terrier',
  'Kangal',
  'Kerry Blue Terrier',
  'Labrador Retriever',
  'Landseer',
  'Leonberg',
  'Lévrier Afghan',
  'Lévrier Whippet',
  'Lhassa Apso',
  'Loulou de Poméranie',
  'Malamute de l\'Alaska',
  'Mastiff',
  'Mâtin de Naples',
  'Montagne des Pyrénées',
  'Pinscher',
  'Pinscher Nain',
  'Pointer Anglais',
  'Rottweiler',
  'Saint-Bernard',
  'Samoyède',
  'Schnauzer',
  'Schnauzer Géant',
  'Schnauzer Nain',
  'Setter Anglais',
  'Setter Gordon',
  'Setter Irlandais',
  'Shar Pei',
  'Shiba Inu',
  'Shih Tzu',
  'Spitz Allemand',
  'Spitz Japonais',
  'Springer Anglais',
  'Staffordshire Bull Terrier',
  'Teckel',
  'Terre-Neuve',
  'Terrier Tibétain',
  'Welsh Corgi',
  'West Highland White Terrier',
  'Yorkshire Terrier',
]

export function getBreedsForSpecies(species: 'cat' | 'dog'): string[] {
  return species === 'cat' ? CAT_BREEDS : DOG_BREEDS
}
