sonar.projectKey=sda-refuge
sonar.projectName=SDA Refuge
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
